### PR TITLE
Various fixes and enhancements; fixes #64, closes #117, closes #177

### LINKED ISSUE #64: [Spotify] Broken when streamer mode enabled
Due to the fact that discriminator is missing in the user account info, so we can't get the style of it
`TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

### LINKED ISSUE #117: Hidden emotes still in autocomplete.
**Describe the bug**
Hidden emotes are not properly hidden from the autocomplete, instead they are invisible.

**To Reproduce**
1) Hide the emotes for the Powercord server.
2) Type `:beta` and then press enter, it will autocomplete to `:betatester:` even if it doesn't show in the autocomplete and other emotes are being shown instead.

**Expected behavior**
It should not autocomplete to `:betatester:`, instead to the first emote shown in the autocomplete if there was one.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Discord version: Release Channel: canary - Build Number: 32982

### LINKED ISSUE #177: Error when clicking gif button
**Describe the bug**
When you click on the gif button, it generates and error in the console (but I couldn't find anything visually wrong)

**To Reproduce**
1. click the gif button
2. open the dev console
3. stare at the error even though visual nothing is effected.

**Expected behavior**
no error?

**Desktop (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - Discord and Powercord version: [You can find it by opening DevTools (Ctrl + Shift + I) and running `powercord.buildInfo`] "Release Channel: canary - Discord's Build Number: 36318 - Powercord's git revision: 5f1a494eafa026f37c3466b198a2ba7040a18391@v2"

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [X] I made sure this is not related to an external plugin or a theme
 
ERROR:
[Powercord:Injector] Failed to run injection "pc-emojiUtility-hideEmojisComplete" TypeError: Cannot read property '0' of undefined
    at t.<anonymous> (C:\Users\jtssh\Documents\Powercord\powercord\src\Powercord\plugins\pc-emojiUtility\index.js:583)
    at C:\Users\jtssh\Documents\Powercord\powercord\src\fake_node_modules\powercord\injector.js:143
    at Array.forEach (<anonymous>)
    at Object._runInjections (C:\Users\jtssh\Documents\Powercord\powercord\src\fake_node_modules\powercord\injector.js:141)
    at t.render (C:\Users\jtssh\Documents\Powercord\powercord\src\fake_node_modules\powercord\injector.js:29)
    at Qi (8d4a3dcbe7e643a5cc25.js:75)
    at $i (8d4a3dcbe7e643a5cc25.js:75)
    at ea (8d4a3dcbe7e643a5cc25.js:75)
    at Ra (8d4a3dcbe7e643a5cc25.js:75)
    at La (8d4a3dcbe7e643a5cc25.js:75)

### PR DESCRIPTION
**Pull request by GriefMoDz**
### Plugin Changelog:

```ini
[Announcements]
    # Notice.jsx:
      - Move 'classesStore' variable inside `constructor()`.
      - Change default value of 'types' to "{}".
      - Replace single-line comment (line 66 -> 67) with a multi-line block.

    # index.js:
      - Remove `_forceUpdate()` and replace all calls with the built-in 'forceUpdateElement' helper method.
      - Update 'onClick' action for "pc-first-welcome" announcement - no longer throws an error and
        actually selects 'Powercord' as well as the last selected channel.

    # manifest.json:
      - Bump version number from '0.1.1' to '0.1.2'.

[Class Name Normalizer]
    # index.js:
      - Resolve 'prototype' being `undefined` (return of the `data-guild-id` data attribute!).

[Clickable Edits]
    # index.js:
      - Similar to the first change of the 'index.js' file for Announcements - remove `forceUpdate` method.
      - Add 'container' to the list of possible edits (TL;DR Images are now double-clickable/editable).

    # manifest.json:
      - Bump version number from '0.1.4' to '0.2.0'.

[Emoji Utility]
    # index.js:
      - Hidden emojis now serve to their name and are actually HIDDEN from autocomplete (closes #117)
        ; also closes #177 as the subject has been eradicated. 

    # index.js / Settings.jsx:
      - Replace all occurrences of `getSortedGuilds` with `getFlattenedGuilds` (resolves missing guilds).

    # manifest.json:
      - Bump version number from '1.3.2' to '1.3.3'.

[Plugin Manager]
    # Explore.jsx:
      - Instead of leaving the 'Open Plugins Folder' button in "Installed Plugins" why not add it here as well.

    # Installed.jsx:
      - Move `openFolder()` to Settings.jsx (let''s make things a little more tidy and less cramp, shall we).
      - Replace folder hyperlinks with some fresh new buttons.

    # Settings.jsx:
      - (please refer to the first change of 'Installed.jsx' found above).

    # style.css:
      - Add additional styling to 'powercord-folders-opener' class (buttons also adapt for light theme users).

    # manifest.json:
      - Bump version number from '0.1.0' to '0.1.1'.

[Spotify]
    # SpotifyPlayer.js:
      - Introduce a condition that checks if an error does in fact exist (should help with false-positives).

    # index.js:
      - Add more classes to 'containerClasses' variable - we''ll use these for fetching class names dynamically within 'Modal.jsx'.

    # style.css:
      - Remove some instances of duplicated attributes (ones that have already been declared by Discord).
      - Make a new class for the volume slider that adds a 10 pixels top-margin.
      - Adjust the spotifyText 'transform' attribute used from 75-100%, fixing the unfinished animation cycle for sliding text. 

    # Modal.jsx:
      - As already brought up in the changes for 'index.js', class names are now retrieved from 'containerClasses'.
      - Reduce width and height for artwork image to "32px" and change the cursor to a pointer when hovered.
      - Advanced controls actually get displayed/are hidden in the Spotify context menu now.

    # Title.jsx:
      - Font size for title is now dynamically set and is persistent over 'Streamer Mode' being enabled (closes #64).
      - Title now properly scrolls through text upon hover (previously used to cut some text off - this has now been
        resolved!).

    # contextMenuGroups.js:
      - Change "Playback Settings" icon to a sync indicator if the repeat state is 'On'.
      - Add text markers to volume slider.

    # manifest.json:
      - Bump version number from '1.0.0' to '1.1.0'.
```

### CODE REVIEW

File: src/Powercord/plugins/pc-spotify/Modal/Title.jsx [hunk 1]
```diff
@@ -11,24 +11,24 @@ module.exports = class Title extends React.Component {
   }
 
   render () {
-    // @todo: make dynamic
-    this.canvas.font = 'normal normal 400 normal 14px / 14px Whitney, "Helvetica Neue", Helvetica, Arial, sans-serif';
+    const titleElement = document.querySelector(`.${this.props.className.replace(/ /g, '.')}`);
+    this.canvas.font = titleElement ? getComputedStyle(titleElement).font : null;
```
Comment (cyyynthia) [inline src/Powercord/plugins/pc-spotify/Modal/Title.jsx:15]: Back when it was dynamic we got issues because the discrim font properties aren't the same, and causes the text to scroll too far. But since streamer mode wipes the discriminator element we can't compute it blablabla

Ig this is good for now:tm:

**Review by cyyynthia — CHANGES_REQUESTED** [review]
so many changes 😳

and 👏 pls 👏 make 👏 travis 👏 happy https://travis-ci.org/powercord-org/powercord/builds/568314498

**Review by cyyynthia — APPROVED** [review]
